config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  devise_for :users
  mount Sidekiq::Web => '/sidekiq'

  resources :miners, only: [:index, :show]
  resources :earnings, only: [:index]
  resources :blocks

  root to: "miners#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/global_info.rb
class GlobalInfo < ApplicationRecord
end

app/models/miner.rb
class Miner < ApplicationRecord
  has_many :miner_infos
end

app/models/miner_info.rb
class MinerInfo < ApplicationRecord
  belongs_to :miner
end

app/models/monero_block.rb
class MoneroBlock < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/blocks_controller.rb
class BlocksController < ApplicationController
  def index
    @monero_blocks = MoneroBlock.all.order(unlocked: :asc, ts: :desc)
  end
end

app/controllers/earnings_controller.rb
class EarningsController < ApplicationController
  def index
    @total_days = (GlobalInfo.last.created_at.to_date - GlobalInfo.first.created_at.to_date).to_i
    @total_earned = GlobalInfo.last.amt_due - GlobalInfo.first.amt_due

    @earned_1d = @total_earned / @total_days
    @earned_1w = @earned_1d * 7
    @earned_1m = @earned_1d * 30
    @earned_1y = @earned_1d * 365

    @url = "https://min-api.cryptocompare.com/data/price?fsym=XMR&tsyms=CHF,USD,EUR"
    @worth = JSON.parse(URI.parse(@url).read)

    @entries = []
    @earnings = []
    GlobalInfo.all.order(amt_due: :asc, created_at: :asc).uniq {|x| x.amt_due}.each_slice(2).each do |slice|
      next if slice.size < 2
      @entries << {id: slice[0].last_hash, title: "#{(slice[1].amt_due - slice[0].amt_due) / 1000000000000.to_f}", start: Time.at(slice[1].last_hash - 3600), end: Time.at(slice[1].last_hash)}
      @earnings << {id: slice[1].id, earned: (slice[1].amt_due - slice[0].amt_due) / 1000000000000.to_f, due: slice[1].amt_due / 1000000000000.to_f, time: Time.at(slice[1].last_hash)}
    end
    @today = GlobalInfo.where(id: @earnings.collect { |x| x[:id] }, last_hash: Date.today.beginning_of_day.to_i..Date.today.end_of_day.to_i)
                       .order(amt_due: :asc)
    @yesterday = GlobalInfo.where(id: @earnings.collect { |x| x[:id] }, last_hash: Date.yesterday.beginning_of_day.to_i..Date.yesterday.end_of_day.to_i)
                           .order(amt_due: :asc)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @entries }
    end
  end
end

app/controllers/miners_controller.rb
class MinersController < ApplicationController
  def index
    @miners = Miner.all.order(identifier: :asc)#.includes(:miner_infos)
    @miner_infos = MinerInfo.order(created_at: :desc).limit(100)
    @info = GlobalInfo.last
  end
  def show
    @miner = Miner.where(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blocks_helper.rb
module BlocksHelper
end

app/helpers/earnings_helper.rb
module EarningsHelper
end

app/helpers/miners_helper.rb
module MinersHelper
end

app/views/blocks/index.html.erb
<h1>Blocks</h1>
<table class="table">
  <thead>
    <tr>
      <th>Hash</th>
      <th>Diff</th>
      <th>Unlocked</th>
      <th>Value</th>
      <th>Ts</th>
    </tr>
  </thead>
  <tbody>
    <% @monero_blocks.each do |m_block| %>
      <tr class="<%= 'table-danger' unless m_block.b_valid %>">
        <td><%= m_block.hash_id %></td>
        <td><%= m_block.diff %></td>
        <td class="<%= m_block.unlocked ? 'text-success' : 'text-warning' %>"><%= m_block.unlocked %></td>
        <td><%= m_block.b_value %></td>
        <td><%= m_block.ts %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/earnings/index.html.erb
<h1>Earnings</h1>
<div class="card-deck">
  <div class="card">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">Yesterday: <%= (@yesterday.last.amt_due - @yesterday.first.amt_due) / 1000000000000.to_f %></li>
      <li class="list-group-item">Today: <%= (@today.last.amt_due - @today.first.amt_due) / 1000000000000.to_f %></li>
    </ul>
  </div>
  <div class="card">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">Day: <%= @earned_1d / 1000000000000.to_f %></li>
      <li class="list-group-item">Week: <%= @earned_1w / 1000000000000.to_f %></li>
      <li class="list-group-item">Month: <%= @earned_1m / 1000000000000.to_f %></li>
    </ul>
  </div>
  <div class="card">
    <ul class="list-group list-group-flush">
      <li class="list-group-item"><%= @worth["USD"] %> USD</li>
      <li class="list-group-item"><%= @worth["CHF"] %> CHF</li>
      <li class="list-group-item"><%= @worth["EUR"] %> EUR</li>
    </ul>
  </div>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Time</th>
      <th>Earned</th>
      <th>Due</th>
    </tr>
  </thead>
  <tbody>
    <% @earnings.each do |earning| %>
      <tr>
        <td><%= earning[:time].in_time_zone('Europe/Zurich').strftime("%c") %></td>
        <td><%= earning[:earned] %></td>
        <td><%= earning[:due] %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div id="earnings-calendars">
</div>

app/views/layouts/_application_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= root_path %>">MonDashi</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="navbarText">
		<ul class="navbar-nav mr-auto">
			<li class="nav-item active">
        <a class="nav-link" href="<%= miners_path %>">Miners<span class="sr-only">(current)</span></a>
			</li>
			<li class="nav-item">
        <a class="nav-link" href="<%= earnings_path %>">Earnings</a>
			</li>
			<li class="nav-item">
        <a class="nav-link" href="<%= blocks_path %>">Blocks</a>
			</li>
		</ul>
		<span class="navbar-text">
			The cake is a lie!
		</span>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Easy online Encoder</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "layouts/application_navbar" %>
    <%= yield %>
  </body>
</html>

app/views/miners/index.html.erb
<h1>
  Dashboard
  <small class="text-muted"><%= @info.hashrate / 1000.to_f %></small>
</h1>
<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>lts</th>
      <th>Hashrate</th>
      <th>Total Hash</th>
      <th>Valid Shares</th>
      <th>Invalid Shares</th>
    </tr>
  </thead>
  <tbody>
    <% @miners.each do |miner| %>
      <% miner_info = @miner_infos.find { |i| i.miner_id == miner.id } %>
      <tr>
        <td><%= miner.identifier %></td>
        <td><%= Time.at(miner_info.lts).to_datetime %></td>
        <td><%= miner_info.hashrate %></td>
        <td><%= miner_info.total_hash %></td>
        <td><%= miner_info.valid_shares %></td>
        <td><%= [miner_info.invalid_shares || 0, miner_info.invalid_shares || 0].join(" / ") %></td>
      </tr>
    <% end %>
  </tbody>
</table>